use iced::Font;

pub const FLUENT_ICONS: Font = Font::with_name("FluentSystemIcons-Resizable");

pub enum Icon {
    AddCircleFilled,
    AddCircleRegular,
    AttachFilled,
    AttachRegular,
    CallEndFilled,
    CallEndRegular,
    CameraFilled,
    CameraRegular,
    CameraOffFilled,
    CameraOffRegular,
    ChatFilled,
    ChatRegular,
    ContactCardFilled,
    ContactCardRegular,
    DeleteFilled,
    DeleteRegular,
    DismissFilled,
    DismissRegular,
    EmojiFilled,
    EmojiRegular,
    FullScreenMaximizeFilled,
    FullScreenMaximizeRegular,
    GlobeFilled,
    GlobeRegular,
    CheckmarkFilled,
    CheckmarkRegular,
    MicFilled,
    MicRegular,
    MicOffFilled,
    MicOffRegular,
    NavigationFilled,
    NavigationRegular,
    PeopleCommunityFilled,
    PeopleCommunityRegular,
    PersonAddFilled,
    PersonAddRegular,
    PersonProhibitedFilled,
    PersonProhibitedRegular,
    SettingsFilled,
    SettingsRegular,
    ShareScreenPersonFilled,
    ShareScreenPersonRegular,
    ShareScreenStartFilled,
    ShareScreenStartRegular,
    ShareScreenStopFilled,
    ShareScreenStopRegular,
    SignOutFilled,
    SignOutRegular,
    Speaker2Filled,
    Speaker2Regular,
}

impl Icon {
    pub fn unicode(&self) -> char {
        match self {
            Icon::AddCircleFilled => '\u{E00E}',
            Icon::AddCircleRegular => '\u{E00F}',
            Icon::AttachFilled => '\u{E1B4}',
            Icon::AttachRegular => '\u{E1B5}',
            Icon::CallEndFilled => '\u{E397}',
            Icon::CallEndRegular => '\u{E398}',
            Icon::CameraFilled => '\u{E3B9}',
            Icon::CameraRegular => '\u{E3BA}',
            Icon::CameraOffFilled => '\u{E3C3}',
            Icon::CameraOffRegular => '\u{E3C4}',
            Icon::ChatFilled => '\u{E40D}',
            Icon::ChatRegular => '\u{E40E}',
            Icon::ContactCardFilled => '\u{E5AC}',
            Icon::ContactCardRegular => '\u{E5AD}',
            Icon::CheckmarkFilled => '\u{E453}',
            Icon::CheckmarkRegular => '\u{E454}',
            Icon::DeleteFilled => '\u{E65E}',
            Icon::DeleteRegular => '\u{E65F}',
            Icon::DismissFilled => '\u{E6B8}',
            Icon::DismissRegular => '\u{E6B9}',
            Icon::EmojiFilled => '\u{E828}',
            Icon::EmojiRegular => '\u{E829}',
            Icon::FullScreenMaximizeFilled => '\u{E926}',
            Icon::FullScreenMaximizeRegular => '\u{E927}',
            Icon::GlobeFilled => '\u{E95C}',
            Icon::GlobeRegular => '\u{E95D}',
            Icon::MicFilled => '\u{EBEB}',
            Icon::MicRegular => '\u{EBEC}',
            Icon::MicOffFilled => '\u{EBEF}',
            Icon::MicOffRegular => '\u{EBF0}',
            Icon::NavigationFilled => '\u{EC41}',
            Icon::NavigationRegular => '\u{EC42}',
            Icon::PeopleCommunityFilled => '\u{ED28}',
            Icon::PeopleCommunityRegular => '\u{ED29}',
            Icon::PersonAddFilled => '\u{ED5E}',
            Icon::PersonAddRegular => '\u{ED5F}',
            Icon::PersonProhibitedFilled => '\u{EDA8}',
            Icon::PersonProhibitedRegular => '\u{EDA9}',
            Icon::SettingsFilled => '\u{EFAC}',
            Icon::SettingsRegular => '\u{EFAD}',
            Icon::ShareScreenPersonFilled => '\u{EFC8}',
            Icon::ShareScreenPersonRegular => '\u{EFC9}',
            Icon::ShareScreenStartFilled => '\u{EFD0}',
            Icon::ShareScreenStartRegular => '\u{EFD1}',
            Icon::ShareScreenStopFilled => '\u{EFD2}',
            Icon::ShareScreenStopRegular => '\u{EFD3}',
            Icon::SignOutFilled => '\u{F026}',
            Icon::SignOutRegular => '\u{F027}',
            Icon::Speaker2Filled => '\u{F09E}',
            Icon::Speaker2Regular => '\u{F09F}',
        }
    }
}
